version: '3'
services:
  db:
    image: postgres:17
    restart: on-failure
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "-c", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
    driver: local